// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibqjbsapotnoeubesdge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlicWpic2Fwb3Rub2V1YmVzZGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNDg3NTIsImV4cCI6MjEwNTgyNDc1Mn0.kNZBPBKdm_KbVtC6y5qi7zjA8mlRVUOITdZgsYrBuMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});